### ISSUE TITLE
Comparison with fd?

### ISSUE THREAD

**Issue by Avi-D-coder** [vishaltelangre/ff#4]
I use [fd](https://github.com/sharkdp/fd). What is the elevator pitch for switching. 
Thanks

**Comment by vishaltelangre** [comment]
I would suggest you to keep using `fd` if you're already familiar and happy with it. The `ff` utility has no fancy or competitive goodies as of now which `fd` does provide. 

I already know that `ff` performs slowly when tried to search using it through a large number of files. I will try to definitely make it a bit faster though.

`ff` has (if not already, then it will have) sensible defaults. I hardly can remember additional command line flags. Which is why I use `rg something` than `grep -Rn "something"`. I don't think `ff` will ever try to compete or replace `fd` or any other popular utilities out there. If `ff` won't work as intended, then even I will stop using it. :)

If you have any suggestions or feedback, please let me know.
